services:

  database:
    image: 'mysql:8.4'
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # 초기 스키마/데이터 스크립트 자동 실행용 (선택)
      # - ./mysql-init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: local_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_user_password
      MYSQL_ROOT_PASSWORD: rootpassword
      TZ: Asia/Seoul # 타임존 설정 (Spring/JPA 시간 이슈 예방)
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-time-zone=+09:00
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: valkey/valkey:9.0.1-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 5

  kafka:
    image: apache/kafka:3.8.1
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data
    environment:
      # KRaft 모드 설정 - Zookeeper 없이 Kafka 자체적으로 메타데이터 관리 (단일 노드)
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      # KRaft Controller 설정
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      # Listener 설정
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'                                       # 브로커 간 통신에 사용할 리스너 (KRaft 모드 설정에서 필수)
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093'               # , PLAINTEXT: 클라이언트 통신용, CONTROLLER: 컨트롤러 내부 통신용(모든 아이피(0.0.0.0) 접속 허용, 운영에서는 주의 필요)
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092'                            # 외부에서 접근할 때 사용할 주소
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT'    # 리스너 보안 프로토콜 매핑
      # 단일 노드 설정
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      # 기본 Topic 설정
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LOG_RETENTION_HOURS: 168
      # 저장 경로
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s

volumes:
  mysql_data:
  redis_data:
  kafka_data:
